#!/run/current-system/sw/bin/bash

while true; do
    xinput set-button-map "Logitech USB Trackball" 1 2 3 4 5 6 7 8 9
    xinput set-int-prop "Logitech USB Trackball" "Evdev Wheel Emulation Button" 8 8
    xinput set-int-prop "Logitech USB Trackball" "Evdev Wheel Emulation" 8 1
    xinput set-int-prop "Logitech USB Trackball" "Evdev Wheel Axes" 8 6 7 4 5
    xinput set-int-prop "Logitech USB Trackball" "Evdev Wheel X Axis" 8 6
    xinput set-prop "Logitech USB Trackball" "libinput Scroll Method Enabled" 0 0 1
    sleep 15
done

